In [15]:
!pip3 install torch torchvision torchaudio

  Using cached torch-1.12.0-cp39-cp39-win_amd64.whl (161.8 MB)
  Using cached torchvision-0.13.0-cp39-cp39-win_amd64.whl (1.1 MB)


In [ ]:
from __future__ import print_function
import torch

In [ ]:
torch.__version__

In [35]:
#Randomly defined matrix
a = torch.empty(6,3)
print(a)

tensor([[9.4251e-26, 5.3109e-43, 9.4271e-26],
        [5.3109e-43, 9.4246e-26, 5.3109e-43],
        [9.4243e-26, 5.3109e-43, 9.4278e-26],
        [5.3109e-43, 9.4265e-26, 5.3109e-43],
        [9.4256e-26, 5.3109e-43, 9.4267e-26],
        [5.3109e-43, 9.4248e-26, 5.3109e-43]])


In [36]:
type(a)

torch.Tensor

In [37]:
a = torch.zeros(4,3 , dtype=torch.long)
print(a)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [38]:
#Converting list into tensor
a = [7.8,5]
type(a)

list

In [39]:
b = torch.tensor(a)
type(b)

torch.Tensor

In [40]:
#torch always take numerical values
a = torch.tensor(['rumman','ahmad'])

ValueError: too many dimensions 'str'

In [42]:
b = torch.tensor([7.8,5])
b

tensor([7.8000, 5.0000])

In [ ]:
#Creating ones

In [46]:
a  = [7.8,5]
type(a)

list

In [47]:
a = torch.tensor(a)
type(a)

torch.Tensor

In [50]:
a = a.new_ones(6,5 , dtype = torch.double) #new methods take in size
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [52]:
a = torch.randn_like(a,dtype = torch.float)   #override dtype
print(a)                                      #Result will be the same size

tensor([[ 0.2639,  0.1914, -1.2224, -0.5177,  0.2817],
        [ 0.3694, -0.0347, -0.7226, -0.2384, -1.7264],
        [ 0.9469, -0.0411, -0.6082, -0.0358, -0.7482],
        [ 0.0068,  1.4623, -0.0754,  1.0874, -0.5555],
        [ 1.0118,  1.7031, -0.0965, -0.6364, -1.9258],
        [ 1.7448,  2.5696, -0.4314, -0.0172,  0.0824]])


In [54]:
print(a.size())

torch.Size([6, 5])


In [ ]:
#Operations

In [56]:
b = torch.rand(6,5)
print(b)

tensor([[0.9409, 0.7892, 0.7601, 0.9179, 0.2514],
        [0.8711, 0.2822, 0.2592, 0.4899, 0.3617],
        [0.8281, 0.1324, 0.1047, 0.1347, 0.8947],
        [0.3480, 0.3005, 0.7073, 0.9418, 0.2531],
        [0.6505, 0.6852, 0.3301, 0.5871, 0.5763],
        [0.3777, 0.9224, 0.5366, 0.6980, 0.3150]])


In [57]:
#ADDITION
print(a+b)

tensor([[ 1.2049,  0.9806, -0.4624,  0.4002,  0.5330],
        [ 1.2405,  0.2476, -0.4634,  0.2516, -1.3647],
        [ 1.7750,  0.0913, -0.5035,  0.0989,  0.1466],
        [ 0.3548,  1.7628,  0.6319,  2.0292, -0.3025],
        [ 1.6623,  2.3883,  0.2335, -0.0493, -1.3495],
        [ 2.1225,  3.4920,  0.1052,  0.6807,  0.3975]])


In [60]:
result = torch.empty(6,5)
result

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0004e-25],
        [5.3109e-43, 2.4779e-26, 5.3109e-43, 3.5749e+14, 5.3109e-43],
        [1.4013e-45, 0.0000e+00, 7.0065e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [61]:
torch.add(a,b , out = result)   #Providing as an argument
print(result)

tensor([[ 1.2049,  0.9806, -0.4624,  0.4002,  0.5330],
        [ 1.2405,  0.2476, -0.4634,  0.2516, -1.3647],
        [ 1.7750,  0.0913, -0.5035,  0.0989,  0.1466],
        [ 0.3548,  1.7628,  0.6319,  2.0292, -0.3025],
        [ 1.6623,  2.3883,  0.2335, -0.0493, -1.3495],
        [ 2.1225,  3.4920,  0.1052,  0.6807,  0.3975]])


In [62]:
#Adds a to b
b

tensor([[0.9409, 0.7892, 0.7601, 0.9179, 0.2514],
        [0.8711, 0.2822, 0.2592, 0.4899, 0.3617],
        [0.8281, 0.1324, 0.1047, 0.1347, 0.8947],
        [0.3480, 0.3005, 0.7073, 0.9418, 0.2531],
        [0.6505, 0.6852, 0.3301, 0.5871, 0.5763],
        [0.3777, 0.9224, 0.5366, 0.6980, 0.3150]])

In [63]:
a

tensor([[ 0.2639,  0.1914, -1.2224, -0.5177,  0.2817],
        [ 0.3694, -0.0347, -0.7226, -0.2384, -1.7264],
        [ 0.9469, -0.0411, -0.6082, -0.0358, -0.7482],
        [ 0.0068,  1.4623, -0.0754,  1.0874, -0.5555],
        [ 1.0118,  1.7031, -0.0965, -0.6364, -1.9258],
        [ 1.7448,  2.5696, -0.4314, -0.0172,  0.0824]])

In [64]:
b.add_(a)
b

tensor([[ 1.2049,  0.9806, -0.4624,  0.4002,  0.5330],
        [ 1.2405,  0.2476, -0.4634,  0.2516, -1.3647],
        [ 1.7750,  0.0913, -0.5035,  0.0989,  0.1466],
        [ 0.3548,  1.7628,  0.6319,  2.0292, -0.3025],
        [ 1.6623,  2.3883,  0.2335, -0.0493, -1.3495],
        [ 2.1225,  3.4920,  0.1052,  0.6807,  0.3975]])

In [65]:
#Index
a

tensor([[ 0.2639,  0.1914, -1.2224, -0.5177,  0.2817],
        [ 0.3694, -0.0347, -0.7226, -0.2384, -1.7264],
        [ 0.9469, -0.0411, -0.6082, -0.0358, -0.7482],
        [ 0.0068,  1.4623, -0.0754,  1.0874, -0.5555],
        [ 1.0118,  1.7031, -0.0965, -0.6364, -1.9258],
        [ 1.7448,  2.5696, -0.4314, -0.0172,  0.0824]])

In [66]:
a[0]

tensor([ 0.2639,  0.1914, -1.2224, -0.5177,  0.2817])

In [67]:
a[0][1]

tensor(0.1914)

In [68]:
a[:,1]

tensor([ 0.1914, -0.0347, -0.0411,  1.4623,  1.7031,  2.5696])

In [69]:
a[:,[2,3]]

tensor([[-1.2224, -0.5177],
        [-0.7226, -0.2384],
        [-0.6082, -0.0358],
        [-0.0754,  1.0874],
        [-0.0965, -0.6364],
        [-0.4314, -0.0172]])

In [70]:
#View (it is used for reshape or resize)

In [72]:
a = torch.randn(3,3)
a

tensor([[ 0.4307,  1.4959,  0.0998],
        [-0.5226, -0.2474, -0.0542],
        [ 0.5317, -0.3530, -1.4957]])

In [80]:
a.size()

torch.Size([3, 3])

In [75]:
b = a.view(9)         #coverted to 1row and 9 columns
b                         

tensor([ 0.4307,  1.4959,  0.0998, -0.5226, -0.2474, -0.0542,  0.5317, -0.3530,
        -1.4957])

In [81]:
b.size()

torch.Size([9])

In [79]:
c = a.view(-1 , 9)   #the size -1 is inferred from other dimensions
c

tensor([[ 0.4307,  1.4959,  0.0998, -0.5226, -0.2474, -0.0542,  0.5317, -0.3530,
         -1.4957]])

In [82]:
c.size()

torch.Size([1, 9])

In [83]:
#Converting a torch tensor to numpy

In [84]:
x = torch.ones(4)
x

tensor([1., 1., 1., 1.])

In [85]:
y = x.numpy()
y

array([1., 1., 1., 1.], dtype=float32)