# !pip install tensorflow==2.5.0

In [2]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x

In [3]:
import tensorflow as tf

hello_constant = tf.constant('Hello world!')
hello_constant

<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
import tensorflow as tf

#Declaring our own constant
hello_constant = tf.constant('Hello world!')

#Session used for output
sess = tf.compat.v1.Session()
print(sess.run(hello_constant))

b'Hello world!'


In [7]:
#Creating variables
A = tf.constant(1234)
A

<tf.Tensor 'Const_3:0' shape=() dtype=int32>

In [8]:
print(sess.run(A))

1234


In [9]:
#1-D array
B = tf.constant([123,456,789])
B

<tf.Tensor 'Const_4:0' shape=(3,) dtype=int32>

In [10]:
print(sess.run(B))

[123 456 789]


In [11]:
#3-D array 
C = tf.constant([[123,456,789] , [222,333,444]])
C

<tf.Tensor 'Const_5:0' shape=(2, 3) dtype=int32>

In [12]:
print(sess.run(C))

[[123 456 789]
 [222 333 444]]


In [13]:
#Placeholder 
#it is variable in which you pass a data into a runtime

In [14]:
#For string 
x = tf.compat.v1.placeholder(tf.string)
print(sess.run(x,feed_dict={x:'hello world'}))

hello world


In [15]:
#Examples for other datasets
x = tf.compat.v1.placeholder(tf.string)
y = tf.compat.v1.placeholder(tf.int32)
z = tf.compat.v1.placeholder(tf.float32)

print(sess.run(x,feed_dict={x:'hello world',y:123 , z:45.67}))
print(sess.run(y,feed_dict={x:'hello world',y:123 , z:45.67}))
print(sess.run(z,feed_dict={x:'hello world',y:123 , z:45.67}))

hello world
123
45.67


In [16]:
#Tensflow math

In [17]:
#Add
x = tf.add(2, 5)
print(sess.run(x))

7


In [18]:
#subtract
y = tf.subtract(5, 3)
print(sess.run(y))

2


In [19]:
#multiply
z = tf.multiply(2, 5)
print(sess.run(z))

10


In [20]:
# Add
a = tf.divide(4, 2)
print(sess.run(a))

2.0


In [21]:
#For math operation You need same datatype

tf.subtract(3,2.0)  #error

TypeError: Expected int32 passed to parameter 'y' of op 'Sub', got 2.0 of type 'float' instead. Error: Expected int32, got 2.0 of type 'float' instead.

In [22]:
#Converting float into integer
sub = tf.subtract(tf.cast(tf.constant(2.0),tf.int32) ,tf.constant(3))
print(sess.run(sub))

-1


In [37]:
#variables
x = tf.Variable(5)

In [40]:
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(x)

5

In [ ]:
#Truncated Normal()

In [46]:
n_features =120
n_labels = 5 
weights = tf.Variable(tf.random.truncated_normal((n_features,n_labels)))
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(weights)

array([[-1.31684721e-01,  8.49163175e-01,  7.13071048e-01,
        -1.34061730e+00,  1.53113163e+00],
       [-7.78323412e-01,  4.51283664e-01,  4.59968537e-01,
         3.37906778e-02,  1.96938664e-01],
       [ 3.42754498e-02, -4.93482128e-02, -2.47237016e-03,
         1.70007706e+00, -9.00755703e-01],
       [ 1.87260854e+00,  4.83700305e-01, -1.58130243e-01,
         5.68253815e-01,  1.96157843e-01],
       [-9.17926490e-01,  3.99022818e-01, -9.05019268e-02,
        -3.63030620e-02, -5.90447366e-01],
       [-8.58446658e-01, -4.24924582e-01,  3.37370872e-01,
        -5.09000361e-01, -9.80465591e-01],
       [ 7.79877603e-01,  8.71226728e-01, -4.13478822e-01,
        -1.24850619e+00,  1.37458098e+00],
       [ 2.50274420e-01, -1.30192661e+00, -4.95912850e-01,
        -1.12911868e+00,  1.30307412e+00],
       [-3.88315797e-01,  1.55932236e+00,  5.14361799e-01,
         8.18513453e-01, -1.20126940e-01],
       [ 1.20668963e-01,  1.31280708e+00, -8.86031389e-01,
         1.30865347e+00

In [48]:
o = tf.random.truncated_normal((n_features,n_labels))
init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(o)

array([[ 2.20287159e-01, -5.81171155e-01,  2.81481892e-02,
         7.46948600e-01, -2.41854265e-01],
       [ 1.43110514e+00, -3.17929536e-01, -9.64797556e-01,
        -1.01603913e+00, -6.96469322e-02],
       [ 3.67685616e-01, -8.25630665e-01,  1.25685596e+00,
         1.21212162e-01, -2.67172921e-02],
       [-2.04927623e-01,  2.44740561e-01, -3.23495060e-01,
         8.11828971e-01, -1.75654745e+00],
       [ 7.23513544e-01, -6.58888340e-01, -2.12075457e-01,
         1.06569242e+00,  6.80351555e-01],
       [ 7.94679880e-01,  3.96394469e-02,  1.78316474e-01,
         2.05952317e-01, -5.59806287e-01],
       [-8.99217427e-01, -4.95251387e-01, -7.05415189e-01,
        -5.57405710e-01, -4.25654203e-02],
       [ 5.51026642e-01,  6.47765279e-01,  6.69574618e-01,
         1.83783245e+00, -9.08557773e-02],
       [-2.15479210e-01,  1.09975803e+00, -1.63549316e+00,
        -1.62518418e+00, -1.24541903e+00],
       [-4.24432188e-01,  1.67569423e+00,  8.61070991e-01,
        -9.91466403e-01

In [49]:
#Zeros

In [50]:
import numpy as np
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))

init = tf.compat.v1.global_variables_initializer() #initialize before output
sess.run(init)
sess.run(bias)

array([0., 0., 0., 0., 0.], dtype=float32)

In [57]:
#Softmax

In [59]:
x = tf.nn.softmax([1.2,0.9,0.4])
sess.run(x)

array([0.45659032, 0.3382504 , 0.20515925], dtype=float32)

In [60]:
#One hot encoding

In [61]:
#Reduce sum
x = tf.reduce_sum([1,2,3,4,5])
sess.run(x)  #gives the sum

15

In [64]:
#Natural log
x = tf.math.log(100.0)
sess.run(x)

4.6051702

In [66]:
#cross entropy 
import tensorflow as tf

softmax_data = [0.7,0.2,0.1]
one_hot_data = [1.0,0.0,0.0]

softmax = tf.compat.v1.placeholder(tf.float32)
one_hot = tf.compat.v1.placeholder(tf.float32)

#Print cross Entropy
cross_entrpy = -tf.reduce_sum(tf.multiply(one_hot_data,tf.math.log(softmax_data)))
sess.run(cross_entrpy)

0.35667497